"""add webinars and slots

Revision ID: 3c1b661e31ed
Revises: d47d7e6d5237
Create Date: 2026-09-13 22:21:12.172276

"""
from datetime import date, time

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1b661e31ed'
down_revision = 'd47d7e6d5237'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webinars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webinar_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    bind = op.get_bind()

    departments_table = sa.table(
        "departments",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
    )
    dept_id_by_name = {
        name: id_ for id_, name in bind.execute(sa.select(departments_table.c.id, departments_table.c.name))
    }

    webinars_table = sa.table(
        "webinars",
        sa.column("id", sa.Integer),
        sa.column("title", sa.String),
        sa.column("description", sa.Text),
        sa.column("department_id", sa.Integer),
        sa.column("price", sa.Float),
        sa.column("duration_minutes", sa.Integer),
        sa.column("is_active", sa.Boolean),
    )
    slots_table = sa.table(
        "slots",
        sa.column("id", sa.Integer),
        sa.column("webinar_id", sa.Integer),
        sa.column("date", sa.Date),
        sa.column("start_time", sa.Time),
        sa.column("end_time", sa.Time),
        sa.column("capacity", sa.Integer),
        sa.column("available_seats", sa.Integer),
        sa.column("is_active", sa.Boolean),
    )

    seed = [
        {
            "title": "Python Programming",
            "description": "Python fundamentals and practical programming",
            "department": "CSE",
            "price": 999,
            "duration_minutes": 60,
            "slot": {"date": date(2026, 9, 20), "start_time": time(10, 0), "end_time": time(11, 0), "capacity": 50},
        },
        {
            "title": "Machine Learning Foundations",
            "description": "Core ML concepts with hands-on examples",
            "department": "AI/ML",
            "price": 1499,
            "duration_minutes": 90,
            "slot": {"date": date(2026, 9, 22), "start_time": time(16, 0), "end_time": time(17, 30), "capacity": 40},
        },
        {
            "title": "Data Visualization with Python",
            "description": "Building clear, effective charts and dashboards",
            "department": "Data Science",
            "price": 1199,
            "duration_minutes": 60,
            "slot": {"date": date(2026, 9, 25), "start_time": time(18, 0), "end_time": time(19, 0), "capacity": 40},
        },
    ]

    for item in seed:
        webinar_id = bind.execute(
            webinars_table.insert()
            .values(
                title=item["title"],
                description=item["description"],
                department_id=dept_id_by_name[item["department"]],
                price=item["price"],
                duration_minutes=item["duration_minutes"],
                is_active=True,
            )
            .returning(webinars_table.c.id)
        ).scalar_one()

        slot = item["slot"]
        bind.execute(
            slots_table.insert().values(
                webinar_id=webinar_id,
                date=slot["date"],
                start_time=slot["start_time"],
                end_time=slot["end_time"],
                capacity=slot["capacity"],
                available_seats=slot["capacity"],
                is_active=True,
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slots')
    op.drop_table('webinars')
    # ### end Alembic commands ###
