"""add reminder_offset_days to notifications

Revision ID: 605d8042a203
Revises: 2842c96037ab
Create Date: 2026-09-13 22:50:42.146035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605d8042a203'
down_revision = '2842c96037ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('reminder_offset_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'reminder_offset_days')
    # ### end Alembic commands ###
